### ISSUE TITLE
update deps interactively or forced.

### ISSUE THREAD

**Issue by gedw99** [aserto-dev/mage-loot#117]
I hit a problem in logger repo ( https://github.com/aserto-dev/logger )  with the dep version being not able to run on darwin and so upgraded it manually to be:
```
---
go:
  gotestsum:
    importPath: "gotest.tools/gotestsum"
    version: "v1.8.2"
  golangci-lint:
    importPath: "github.com/golangci/golangci-lint/cmd/golangci-lint"
    version: "v1.43.0"
```

It would be cool to be able to ask mage to do it for me.

https://github.com/oligot/go-mod-upgrade allows updating golang modules interatively and works very well. Saves lots of time and can also be run in CI just like mage-loot. You can also force it.

I was thinking about if it's possible to do the same for the golang modules we have in the deps file ?
